name: Auto Assign Copilot SWE Agent to Labeled Issues

on:
  issues:
    types: [labeled]

jobs:
  assign-copilot:
    if: github.event.label.name == 'copilot'
    runs-on: ubuntu-latest
    steps:
      - name: Assign Copilot SWE Agent
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['Copilot']
            })
